import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, BorderStyle } from 'docx';
import { saveAs } from 'file-saver';
import { format } from 'date-fns';

export const downloadTemplateAsDOCX = async (template: any, org: any) => {
  // Replace Placeholders
  let html = template.contentHtml || '';
  html = html.replace(/\{\{ORGANISATION_NAME\}\}/g, org?.displayName || 'Organisation');
  html = html.replace(/\{\{DATE\}\}/g, format(new Date(), 'dd MMM yyyy'));
  html = html.replace(/\{\{REGULATORY_FRAMEWORK\}\}/g, org?.regulatoryFramework || 'FCA / JMLSG');

  // Strip arbitrary HTML logic (simplified parser for MVP docx generation)
  const tempDiv = window.document.createElement('div');
  tempDiv.innerHTML = html;

  const children = Array.from(tempDiv.childNodes);
  const docxElements: any[] = [];

  children.forEach(node => {
     if (node.nodeType === 1) {
        const el = node as HTMLElement;
        const text = el.textContent || '';
        
        switch (el.tagName) {
          case 'H1':
            docxElements.push(new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { before: 400, after: 200 } }));
            break;
          case 'H2':
            docxElements.push(new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 120 } }));
            break;
          case 'H3':
            docxElements.push(new Paragraph({ text, heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 120 } }));
            break;
          case 'P':
            docxElements.push(new Paragraph({ children: [new TextRun(text)], spacing: { after: 120 } }));
            break;
          case 'UL':
          case 'OL':
            Array.from(el.children).forEach(li => {
               docxElements.push(new Paragraph({ text: li.textContent || '', bullet: { level: 0 }, spacing: { after: 100 } }));
            });
            break;
          default:
            if (text.trim()) docxElements.push(new Paragraph({ text, spacing: { after: 120 } }));
        }
     }
  });

  const doc = new Document({
    sections: [{
      properties: { },
      headers: {
        default: null // Explicit null for MVP (requires complex docx Table instantiation for headers usually)
      },
      children: [
        new Paragraph({
          text: template.templateName,
          heading: HeadingLevel.TITLE,
          spacing: { after: 400 }
        }),
        ...docxElements,
        new Paragraph({
           text: `Generated by RegShield AI · Confidential · ${format(new Date(), 'dd MMM yyyy')}`,
           spacing: { before: 800 }
        })
      ]
    }]
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${template.templateName.replace(/\s+/g, '_')}_${format(new Date(), 'yyyyMMdd')}.docx`);
  
  // Simulated audit log POST placeholder
  console.log('Audit Log: template_downloaded trigger');
};
